# Generated by Django 4.0.1 on 2022-10-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_composer_nationality_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composer',
            old_name='nationality_name',
            new_name='nationalityName',
        ),
    ]
