# Generated by Django 4.0.1 on 2022-09-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_composer_birthdate_remove_composer_deathdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='death',
            field=models.IntegerField(blank=True),
        ),
    ]
