# Generated by Django 4.0.1 on 2022-10-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_composer_nationalityname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composer',
            name='middleName',
        ),
        migrations.AddField(
            model_name='composer',
            name='bio_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='composer',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
