# Generated by Django 4.0.1 on 2022-10-07 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_composer_middlename_composer_bio_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='composer_website',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='composer',
            name='bio_source',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='composer',
            name='biography',
            field=models.TextField(blank=True, default='No Information Available, Check Back Later', null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='publisher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.publisher'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='recording_link',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='score_link',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
