# Generated by Django 4.0.1 on 2022-09-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_composer_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='death',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
