# Generated by Django 4.0.1 on 2022-09-28 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_composer_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.publisher'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='recording_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='score_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
