# Generated by Django 4.0.1 on 2022-09-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_composition_duration_alter_composition_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='recording_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='score_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
