# Generated by Django 4.0.1 on 2022-10-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_blogpost_blogcomment'),
        ('backend', '0009_alter_blogcomment_author_alter_blogpost_author_and_more'),
    ]

    operations = [
    ]
