# Generated by Django 4.0.1 on 2022-09-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_composition_recording_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
