# Generated by Django 4.0.1 on 2022-10-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_forumpost_votes_alter_blogcomment_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_images'),
        ),
    ]
