# Generated by Django 4.0.1 on 2022-10-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_forumpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../static/forums/images'),
        ),
    ]
