# Generated by Django 4.0.1 on 2022-09-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_composer_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composer',
            old_name='features',
            new_name='featured',
        ),
    ]
