# Generated by Django 4.0.1 on 2022-09-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rename_features_composer_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='image',
            field=models.CharField(default='https://i.picsum.photos/id/634/200/200.jpg?hmac=3WUmj9wMd1h3UZICk1C5iydU5fixjx0px9jw-LBezgg', max_length=300),
        ),
    ]
