# Generated by Django 4.0.1 on 2022-10-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositioninstrument',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='compositioninstrument',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.instrument'),
        ),
    ]
