# Generated by Django 4.0.1 on 2022-10-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_compositioninstrument_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='image',
            field=models.CharField(default='/static/composers/images/Default.png', max_length=300),
        ),
    ]
