# Generated by Django 4.0.1 on 2022-10-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_composer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
