# Generated by Django 4.0.1 on 2022-10-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='../static/users/images/Default_profile_pic.png', upload_to='../static/users/images'),
        ),
    ]
