# Generated by Django 4.0.1 on 2022-10-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='authenticated',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tier',
        ),
    ]
